---
recipes:
  - zlib
  - openssl
  - b2 # Needed by boost
  - bzip2 # Needed by boost
  - libbacktrace # Needed by boost
  - boost
  - nlohmann_json
  - fmt
  - gtest
  - eigen
  - catch2
  - libiconv
  - rapidjson
  - zstd
  - sqlite3
  - spdlog
  - pkgconf
  - libjpeg
  - xz_utils
  - expat
  - m4
  - libpng
  - libwebp
  - opengl
  - cli11
  - libtool # Needed by libcurl and libuuid
  - libcurl
  - autoconf
  - protobuf
  - automake
  - c-ares
  - jbig
  - libuuid
  - xorg
  - ninja
  - ms-gsl
  - libpq
  - cpp-httplib
  - libxml2
  - pybind11
  - brotli
  - abseil
  - freetype
  - libffi
  - pcre
  - libdeflate
  - wayland
  - grpc
  - pcre2
  - yaml-cpp
  - asio
  - meson # Needed by wayland-protocols
  - wayland-protocols
  - opus
  - gnu-config
  - libtiff
  - re2
  - poco
  - xkeyboard-config # Needed by xkbcommon
  - xkbcommon
  - ogg
  - jasper
  - jsoncpp
  - glm
  - libuv
  - libsodium
  - lz4
  - range-v3
  - vorbis
  - flex
  - cmake # Needed by benchmark
  - benchmark
  - fontconfig
  - openjpeg
  - imath # Needed for openexr
  - openexr
  - aws-c-common
  - md4c
  - magic_enum
  - cppcodec
  - glfw
  - nasm # Needed by openh264 and libjpeg-turbo
  - openh264
  - cyrus-sasl
  - bison
  - zulu-openjdk
  - libelf # Needed by glib
  - glib
  - libunwind
  - libjpeg-turbo
  - ghc-filesystem
  - nanoflann
  - glu
  - stb
  - libmysqlclient
  - cxxopts
  - odbc
  - libcap
  - mbedtls
  - cereal
  - cryptopp
  - civetweb
  - sdl
  - xtl
  - xsimd # Needed by xtensor
  - xtensor
  - minizip
  - icu
  - libalsa
  - picojson # Needed by jwt-cpp
  - jwt-cpp
