core.sources:download_urls=["https://superfrogchrismc.jfrog.io/artifactory/api/generic/cfi-backup-sources", "origin"]
core.sources:upload_url=https://superfrogchrismc.jfrog.io/artifactory/api/generic/cfi-backup-sources
