name: 2.0 Migration Effort Check

on:
  push:

jobs:
  create:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9 # Should be 3.6 for 2.0 min (my code uses 3.9 features)
    - name: install cmake
      uses: lukka/get-cmake@latest # Should be set to CMake 3.15 which is the min for 2.0

    #- run: python3 -m pip install "conan @ git+https://github.com/conan-io/conan.git@develop2"
    - run: python3 -m pip install conan==2.0.9
    - name: conan config
      run: |
        echo '## ConanCenterIndex 2.0 Migration Effort' >> $GITHUB_STEP_SUMMARY
        echo 'This workflow will export and build all the package the represent (or are required for) the top 80% or downloaded packages' >> $GITHUB_STEP_SUMMARY
        conan config home
        conan config install .conan
        conan profile detect --name default
      shell: bash

    - name: conan export
      run: conan cci:export-all-versions --list=.github/top_100_recipes.yaml -f md >> $GITHUB_STEP_SUMMARY
      shell: bash

    - name: conan create
      env:
        CFI_TOKEN: ${{ secrets.CONAN_REMOTE_PW }}
      run: conan cci:create-top-versions --list=.github/top_100_recipes.yaml -pr default -pr install_sytem_tools -f md >> $GITHUB_STEP_SUMMARY
      shell: bash

    - name: conan remote
      run: |
        conan remote enable cci-fork
        conan remote login cci-fork christopherm@jfrog.com -p ${{ secrets.CONAN_REMOTE_PW }}

    - name: conan upload
      env:
        CFI_TOKEN: ${{ secrets.CONAN_REMOTE_PW }}
      run: conan upload "*" -c -r cci-fork

  andoird:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9 # Should be 3.6 for 2.0 min (my code uses 3.9 features)
    - name: install cmake
      uses: lukka/get-cmake@latest # Should be set to CMake 3.15 which is the min for 2.0

    #- run: python3 -m pip install "conan @ git+https://github.com/conan-io/conan.git@develop2"
    - run: python3 -m pip install conan==2.0.9
    - name: conan config
      run: |
        echo '## ConanCenterIndex Android Support Effort' >> $GITHUB_STEP_SUMMARY
        echo 'This workflow will export and build all the package which are not to support andoid' >> $GITHUB_STEP_SUMMARY
        conan config home
        conan config install .conan
        conan profile detect --name default
      shell: bash

    - name: conan export
      run: conan cci:export-all-versions --list=.github/top_100_recipes.yaml -f md >> $GITHUB_STEP_SUMMARY
      shell: bash

    - name: conan create
      env:
        CFI_TOKEN: ${{ secrets.CONAN_REMOTE_PW }}
      run: conan cci:create-top-versions --list=.github/android_support.yaml -pr android -f md >> $GITHUB_STEP_SUMMARY
      shell: bash

    - name: conan remote
      run: |
        conan remote enable cci-fork
        conan remote login cci-fork christopherm@jfrog.com -p ${{ secrets.CONAN_REMOTE_PW }}

    - name: conan upload
      env:
        CFI_TOKEN: ${{ secrets.CONAN_REMOTE_PW }}
      run: conan upload "*" -c -r cci-fork
